
trigger:
- master

variables:
  DEPOT_TOOLS_WIN_TOOLCHAIN: '0'
  DEPOT_TOOLS_METRICS: '0'
  PYTHON_HOME: ''
  SKIA_REVISION: '9db7378d72bc18d10c40d73e75dd7920849167c9'
  PYTHONWARNINGS: 'ignore:DEPRECATION::pip._internal.cli.base_command'
  GCLIENT_PY3: '1'

jobs:
- job: Build_Skia
  timeoutInMinutes: 0
  pool:
   vmImage: 'windows-latest'
  steps:
  - powershell: |
      Invoke-WebRequest -Uri "https://storage.googleapis.com/chrome-infra/depot_tools.zip" -OutFile depot_tools.zip
      &7z x depot_tools.zip -odepot_tools
      Remove-Item depot_tools.zip
    displayName: 'Fetch depot_tools'
