
trigger:
- master

variables:
  DEPOT_TOOLS_WIN_TOOLCHAIN: '0'
  DEPOT_TOOLS_METRICS: '0'
  PYTHON_HOME: ''
  SKIA_REVISION: '9db7378d72bc18d10c40d73e75dd7920849167c9'
  PYTHONWARNINGS: 'ignore:DEPRECATION::pip._internal.cli.base_command'
  GCLIENT_PY3: '1'

jobs:
- job: Build_Docker
  timeoutInMinutes: 0
  pool:
   vmImage: 'windows-latest'
  steps:
  - powershell: |
      Install-Module "DockerMsftProvider" -Force
      Update-Module "DockerMsftProvider"
      Install-Package Docker -ProviderName "DockerMsftProvider" -Update -Force
      Set-Content -Value "`{`"experimental`":true`}" -Path C:\ProgramData\docker\config\daemon.json
      restart-service docker
      docker run --hostname=a2b729836f8b --mac-address=02:42:ac:11:00:02 --env=MYSQL_ROOT_PASSWORD=test --env=PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin --env=GOSU_VERSION=1.17 --env=MYSQL_MAJOR=innovation --env=MYSQL_VERSION=9.1.0-1.el9 --env=MYSQL_SHELL_VERSION=9.1.0-1.el9 --volume=/var/lib/mysql --workdir=/ --restart=no --runtime=runc -d mysql:latest
    displayName: 'docker run'
